name: solar system workflow

on:
    workflow_dispatch:
    push:
        branches:
            - 'feature-*'


jobs:
    unit-testing:
        name: Unit Testing
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repo
              uses: actions/checkout@v4
            
            - name: setup Node.js
              uses: actions/setup-node@v3
              with:
                node-version: 18
            
            - name: Install Dependencies
              run: npm install

            - name: Run Unit Tests
              run: npm test
              
    
